### ISSUE TITLE
Fine tuning - RetrieveJobResponseHyperparameters constructor fails

### ISSUE THREAD

**Issue by bekoval** [openai-php/client#214]
```
OpenAI\Responses\FineTuning\RetrieveJobResponseHyperparameters::__construct(): Argument #1 ($nEpochs) must be of type int, string given, called in /api/vendor/openai-php/client/src/Responses/FineTuning/RetrieveJobResponseHyperparameters.php on line 33 {"exception":"[object] (TypeError(code: 0): OpenAI\\Responses\\FineTuning\\RetrieveJobResponseHyperparameters::__construct(): Argument #1 ($nEpochs) must be of type int, string given, called in /api/vendor/openai-php/client/src/Responses/FineTuning/RetrieveJobResponseHyperparameters.php on line 33 at /api/vendor/openai-php/client/src/Responses/FineTuning/RetrieveJobResponseHyperparameters.php:20)
[stacktrace]
#0 /api/vendor/openai-php/client/src/Responses/FineTuning/RetrieveJobResponseHyperparameters.php(33): OpenAI\\Responses\\FineTuning\\RetrieveJobResponseHyperparameters->__construct('auto')
#1 /api/vendor/openai-php/client/src/Responses/FineTuning/RetrieveJobResponse.php(62): OpenAI\\Responses\\FineTuning\\RetrieveJobResponseHyperparameters::from(Array)
#2 /api/vendor/openai-php/client/src/Resources/FineTuning.php(34): OpenAI\\Responses\\FineTuning\\RetrieveJobResponse::from(Array, Object(OpenAI\\Responses\\Meta\\MetaInformation))
```

The constructor param $nEpochs is defined as int, for some reason string `auto` has passed

**Comment by gehrisandro** [comment]
Hi @bekoval 

Thanks for your report.
